# Simple NFS Daemon Configuration
# Basic configuration for development and testing

server:
  # Network configuration
  bind_address: "0.0.0.0"
  port: 2049
  
  # Protocol support
  enable_tcp: true
  enable_udp: true
  enable_nfsv2: true
  enable_nfsv3: true
  enable_nfsv4: false
  
  # Performance settings
  max_connections: 100
  read_buffer_size: 8192
  write_buffer_size: 8192
  
  # File system settings
  root_path: "/var/lib/simple-nfsd/shares"
  max_file_size: 1073741824  # 1GB

logging:
  # Logging configuration
  log_level: "INFO"
  log_file: "/var/log/simple-nfsd/simple-nfsd.log"
  log_max_size: 10485760  # 10MB
  log_max_files: 5

security:
  # Security settings
  security_mode: "sys"
  root_squash: true
  all_squash: false
  anon_uid: 65534
  anon_gid: 65534
  
  # Authentication
  auth_sys_enabled: true
  auth_dh_enabled: false

exports:
  # Export configuration
  - path: "/home/shared"
    clients: "*"
    options: ["rw", "sync", "no_root_squash"]
  - path: "/tmp/public"
    clients: "*"
    options: ["ro", "sync", "all_squash"]
