# Simple NFS Daemon Configuration - Simple Setup
# This is a basic configuration for simple NFS sharing

server:
  listen_address: "0.0.0.0"
  listen_port: 2049
  root_path: "/var/lib/simple-nfsd/shares"
  enable_tcp: true
  enable_udp: true
  max_connections: 10

security:
  enable_auth: true
  allow_anonymous: false
  auth_methods:
    - "AUTH_SYS"

logging:
  log_level: "info"
  log_file: "/var/log/simple-nfsd.log"
  max_log_size: "10MB"
  max_log_files: 5

shares:
  public:
    path: "/var/lib/simple-nfsd/shares/public"
    read_only: false
    allowed_clients:
      - "192.168.1.0/24"
    options:
      sync: true
      no_subtree_check: true